VERTEX_MOVIE = 'movie'
VERTEX_PERSON = 'person'
VERTEX_USER = 'user'
VERTEX_GENRE = 'genre'

EDGE_ACTOR = 'actor'
EDGE_RATED = 'rated'
EDGE_BELONGS_TO = "belongsTo"
EDGE_KNOWS = "knows"

KEY_AGE = 'age'
KEY_COUNTRY = 'country'
KEY_DEGREE = '_degree'
KEY_DISTRIBUTION = '_distribution'
KEY_DURATION = 'duration'
KEY_IN_DEGREE = '_inDegree'
KEY_MOVIE_ID = 'movieId'
KEY_NAME = 'name'
KEY_OUT_DEGREE = '_outDegree'
KEY_PERSON_ID = 'personId'
KEY_PRODUCTION = 'production'
KEY_RATING = 'rating'
KEY_TITLE = 'title'
KEY_USER_ID = 'userId'
KEY_VERTEX = '_vertex'
KEY_YEAR = 'year'
