VERTEX_MOVIE = 'movie'
VERTEX_PERSON = 'person'
VERTEX_USER = 'user'

EDGE_ACTOR = 'actor'
EDGE_RATED = 'rated'

KEY_AGE = 'age'
KEY_COUNTRY = 'country'
KEY_DURATION = 'duration'
KEY_MOVIE_ID = 'movieId'
KEY_NAME = 'name'
KEY_PERSON_ID = 'personId'
KEY_PRODUCTION = 'production'
KEY_RATING = 'rating'
KEY_TITLE = 'title'
KEY_USER_ID = 'userId'
KEY_YEAR = 'year'
