//propertyKey definition
schema.propertyKey('pp').Int().single().create()
schema.propertyKey('species_id').Int().single().create()
schema.propertyKey('game_index').Int().single().create()
schema.propertyKey('gender').Text().single().create()
schema.propertyKey('egg_groups').Text().single().create()
schema.propertyKey('accuracy').Int().single().create()
schema.propertyKey('type').Text().single().create()
schema.propertyKey('stat_id').Int().single().create()
schema.propertyKey('location_id').Int().single().create()
schema.propertyKey('pocket_id').Int().single().create()
schema.propertyKey('category_id').Int().single().create()
schema.propertyKey('move_id').Int().single().create()
schema.propertyKey('pokemon_id').Int().single().create()
schema.propertyKey('ability_id').Int().single().create()
schema.propertyKey('ability').Text().single().create()
schema.propertyKey('power').Int().single().create()
schema.propertyKey('height').Int().single().create()
schema.propertyKey('item').Text().single().create()
schema.propertyKey('stat').Text().single().create()
schema.propertyKey('cost').Int().single().create()
schema.propertyKey('pokemon').Text().single().create()
schema.propertyKey('item_id').Int().single().create()
schema.propertyKey('level').Int().single().create()
schema.propertyKey('base_experience').Int().single().create()
schema.propertyKey('type_id').Int().single().create()
schema.propertyKey('region_id').Int().single().create()
schema.propertyKey('weight').Int().single().create()
schema.propertyKey('gender_id').Int().single().create()
schema.propertyKey('priority').Text().single().create()
schema.propertyKey('pocket_type').Text().single().create()
schema.propertyKey('egg_groups_id').Int().single().create()
schema.propertyKey('moves').Text().single().create()
schema.propertyKey('base_stat').Int().single().create()
schema.propertyKey('location').Text().single().create()
schema.propertyKey('effect_chance').Int().single().create()
schema.propertyKey('region').Text().single().create()
schema.propertyKey('category').Text().single().create()
schema.propertyKey('rarity').Text().single().create()

//vertexLabel definition
schema.vertexLabel('item_pockets').properties('pocket_id', 'pocket_type').create()
schema.vertexLabel('stat').properties('stat_id', 'stat').create()
schema.vertexLabel('pokemon').properties('weight', 'species_id', 'pokemon_id', 'pokemon', 'base_experience', 'height').create()
schema.vertexLabel('egg').properties('egg_groups_id', 'egg_groups').create()
schema.vertexLabel('type').properties('type', 'type_id').create()
schema.vertexLabel('item_category').properties('category_id', 'item_id').create()
schema.vertexLabel('abilities').properties('ability_id', 'ability').create()
schema.vertexLabel('moves').properties('moves', 'power', 'pp', 'effect_chance', 'priority', 'move_id', 'accuracy').create()
schema.vertexLabel('location').properties('location', 'game_index', 'region_id', 'location_id').create()
schema.vertexLabel('region').properties('region', 'region_id').create()
schema.vertexLabel('items').properties('cost', 'category_id', 'item_id', 'item').create()

//edgeLabel definition
schema.edgeLabel('hatches_from').connection('pokemon', 'egg').create()
schema.edgeLabel('has_pocket_type').connection('item_category', 'item_pockets').create()
schema.edgeLabel('has_move').properties('level').connection('pokemon', 'moves').create()
schema.edgeLabel('uses_item').properties('rarity').connection('pokemon', 'items').create()
schema.edgeLabel('has_type').connection('pokemon', 'type').create()
schema.edgeLabel('has_category').properties('pocket_id', 'category').connection('items', 'item_category').create()
schema.edgeLabel('is_in_region').connection('location', 'region').create()
schema.edgeLabel('evolves_to').connection('pokemon', 'pokemon').create()
schema.edgeLabel('has_stat').properties('base_stat').connection('pokemon', 'stat').create()
schema.edgeLabel('has_ability').connection('pokemon', 'abilities').create()
schema.edgeLabel('has_location').connection('pokemon', 'location').create()

//Index definition
schema.vertexLabel('location').index('bygame_index').materialized().by('game_index').add()
schema.vertexLabel('region').index('byregion_id').materialized().by('region_id').add()
schema.vertexLabel('location').index('bylocation_id').materialized().by('location_id').add()
schema.vertexLabel('stat').index('bystat_id').materialized().by('stat_id').add()
schema.vertexLabel('item_pockets').index('bypocket_id').materialized().by('pocket_id').add()
schema.vertexLabel('moves').index('bymove_id').materialized().by('move_id').add()
schema.vertexLabel('abilities').index('byability_id').materialized().by('ability_id').add()
schema.vertexLabel('items').index('byitem_id').materialized().by('item_id').add()
schema.vertexLabel('type').index('bytype_id').materialized().by('type_id').add()
schema.vertexLabel('egg').index('byegg_groups_id').materialized().by('egg_groups_id').add()
schema.vertexLabel('item_category').index('bycategory_id').materialized().by('category_id').add()
schema.vertexLabel('pokemon').index('bypokemon_id').materialized().by('pokemon_id').add()
schema.vertexLabel('pokemon').index('bypokemon_name').materialized().by('pokemon').add()
