//propertyKey definition
schema.propertyKey('pp').Int().single().create()
schema.propertyKey('species_id').Int().single().create()
schema.propertyKey('game_index').Int().single().create()
schema.propertyKey('gender').Text().single().create()
schema.propertyKey('egg_groups').Text().single().create()
schema.propertyKey('accuracy').Int().single().create()
schema.propertyKey('type').Text().single().create()
schema.propertyKey('stat_id').Int().single().create()
schema.propertyKey('location_id').Int().single().create()
schema.propertyKey('pocket_id').Int().single().create()
schema.propertyKey('category_id').Int().single().create()
schema.propertyKey('move_id').Int().single().create()
schema.propertyKey('pokemon_id').Int().single().create()
schema.propertyKey('ability_id').Int().single().create()
schema.propertyKey('ability').Text().single().create()
schema.propertyKey('power').Int().single().create()
schema.propertyKey('height').Int().single().create()
schema.propertyKey('item').Text().single().create()
schema.propertyKey('stat').Text().single().create()
schema.propertyKey('cost').Int().single().create()
schema.propertyKey('pokemon').Text().single().create()
schema.propertyKey('item_id').Int().single().create()
schema.propertyKey('level').Int().single().create()
schema.propertyKey('base_experience').Int().single().create()
schema.propertyKey('type_id').Int().single().create()
schema.propertyKey('region_id').Int().single().create()
schema.propertyKey('weight').Int().single().create()
schema.propertyKey('gender_id').Int().single().create()
schema.propertyKey('priority').Text().single().create()
schema.propertyKey('pocket_type').Text().single().create()
schema.propertyKey('egg_groups_id').Int().single().create()
schema.propertyKey('moves').Text().single().create()
schema.propertyKey('base_stat').Int().single().create()
schema.propertyKey('location').Text().single().create()
schema.propertyKey('effect_chance').Int().single().create()
schema.propertyKey('region').Text().single().create()
schema.propertyKey('category').Text().single().create()
schema.propertyKey('rarity').Text().single().create()

//vertexLabel definition
schema.vertexLabel('item_pockets').partitionKey('pocket_id').properties('pocket_type').create()
schema.vertexLabel('stat').partitionKey('stat_id').properties('stat').create()
schema.vertexLabel('pokemon').partitionKey('pokemon_id').properties('weight', 'species_id', 'pokemon', 'base_experience', 'height').create()
schema.vertexLabel('egg').partitionKey('egg_groups_id').properties('egg_groups').create()
schema.vertexLabel('type').partitionKey('type_id').properties('type').create()
schema.vertexLabel('item_category').partitionKey('category_id').properties('item_id').create()
schema.vertexLabel('abilities').partitionKey('ability_id').properties('ability').create()
schema.vertexLabel('moves').partitionKey('move_id').properties('moves', 'power', 'pp', 'effect_chance', 'priority', 'accuracy').create()
schema.vertexLabel('location').partitionKey('location_id').properties('location', 'game_index', 'region_id').create()
schema.vertexLabel('region').partitionKey('region_id').properties('region').create()
schema.vertexLabel('items').partitionKey('item_id').properties('cost', 'category_id', 'item').create()

//edgeLabel definition
schema.edgeLabel('hatches_from').connection('pokemon', 'egg').create()
schema.edgeLabel('has_pocket_type').connection('item_category', 'item_pockets').create()
schema.edgeLabel('has_move').properties('level').connection('pokemon', 'moves').create()
schema.edgeLabel('uses_item').properties('rarity').connection('pokemon', 'items').create()
schema.edgeLabel('has_type').connection('pokemon', 'type').create()
schema.edgeLabel('has_category').properties('pocket_id', 'category').connection('items', 'item_category').create()
schema.edgeLabel('is_in_region').connection('location', 'region').create()
schema.edgeLabel('evolves_to').connection('pokemon', 'pokemon').create()
schema.edgeLabel('has_stat').properties('base_stat').connection('pokemon', 'stat').create()
schema.edgeLabel('has_ability').connection('pokemon', 'abilities').create()
schema.edgeLabel('has_location').connection('pokemon', 'location').create()

//Index definition
schema.vertexLabel('location').index('bygame_index').materialized().by('game_index').add()
schema.vertexLabel('pokemon').index('bypokemon_name').materialized().by('pokemon').add()
